### ISSUE TITLE
Country Specific URLs

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#159]
Some sites have different websites for different countries. 

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/67381/77330222-eeb88680-6d16-11ea-8459-f9293e0dd518.png">

Maybe some YAML like this:

```yaml
  url: https://toogoodtogo.com
  countryUrls: 
    "no": https://toogoodtogo.no
    ch: https://toogoodtogo.ch
```

Making a little helper to grab the data, so its the default URL unless you've selected a country, then it'll try to use that if it exists.
